"""Pydantic models for audit reports and fetcher results."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Fetcher layer models
# ---------------------------------------------------------------------------


class FetcherResult(BaseModel):
    """Result from a single upstream data source."""

    source: str
    success: bool = True
    data: dict[str, Any] = Field(default_factory=dict)
    error: str = ""


class AggregatedData(BaseModel):
    """Merged data from all upstream sources, ready for the risk engine."""

    # Token identity
    token_name: str | None = None
    token_symbol: str | None = None

    # Contract security (from GoPlus / RugCheck)
    is_mintable: bool | None = None
    is_freezable: bool | None = None
    is_closable: bool | None = None
    is_metadata_mutable: bool | None = None

    # Holder distribution (from GoPlus)
    top10_holder_pct: float | None = None
    holder_count: int | None = None

    # Liquidity (from DexScreener / GoPlus / RugCheck)
    liquidity_usd: float | None = None
    lp_burned_pct: float | None = None   # GoPlus: permanently destroyed LP (0-100)
    lp_locked_pct: float | None = None   # RugCheck: locked LP, may unlock later (0-100)

    # Market data (from DexScreener)
    price_usd: float | None = None
    volume_24h_usd: float | None = None
    buy_count_24h: int | None = None
    sell_count_24h: int | None = None
    pair_created_at: datetime | None = None

    # RugCheck specific
    rugcheck_score: float | None = None  # RugCheck's own risk score
    rugcheck_risks: list[str] = Field(default_factory=list)

    # Source tracking
    sources_succeeded: list[str] = Field(default_factory=list)
    sources_failed: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Risk engine output models
# ---------------------------------------------------------------------------


class RiskLevel(str, Enum):
    SAFE = "SAFE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskFlag(BaseModel):
    level: str
    message: str


class ActionLayer(BaseModel):
    """Layer 1: Machine-readable action signals."""

    is_safe: bool
    risk_level: RiskLevel
    risk_score: int = Field(ge=0, le=100)


class AnalysisLayer(BaseModel):
    """Layer 2: LLM-friendly reasoning."""

    summary: str
    red_flags: list[RiskFlag] = Field(default_factory=list)
    green_flags: list[RiskFlag] = Field(default_factory=list)


class EvidenceLayer(BaseModel):
    """Layer 3: Raw data for human verification."""

    token_name: str | None = None
    token_symbol: str | None = None
    price_usd: float | None = None
    liquidity_usd: float | None = None
    volume_24h_usd: float | None = None
    top_10_holders_pct: float | None = None
    is_mintable: bool | None = None
    is_freezable: bool | None = None
    is_closable: bool | None = None
    lp_burned_pct: float | None = None
    lp_locked_pct: float | None = None
    pair_created_at: str | None = None
    holder_count: int | None = None
    rugcheck_score: float | None = None


class AuditMetadata(BaseModel):
    """Metadata about the audit request."""

    data_sources: list[str] = Field(default_factory=list)
    data_completeness: str = "unknown"  # "full" | "partial" | "minimal" | "unavailable" | "unknown"
    cache_hit: bool = False
    data_age_seconds: int | None = None
    response_time_ms: int = 0
    disclaimer: str = (
        "This report is generated by automated data aggregation. "
        "Not financial advice (NFA). Trade at your own risk."
    )


class AuditReport(BaseModel):
    """Complete three-layer audit report."""

    contract_address: str
    chain: str = "solana"
    audit_timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    degraded: bool = False

    action: ActionLayer
    analysis: AnalysisLayer
    evidence: EvidenceLayer
    metadata: AuditMetadata
